### PR TITLE
WIP: Add PGP Support

### PR DESCRIPTION
**Pull request by j-delaney**
Does not support delegation yet. Two questions I want opinions on:

1. At the moment I have near-duplicate functions (e.g. `createPGPPasswordRec` and `createPasswordRec`) which do almost the same thing with one minor difference. Do you think the proper way to handle this sort of thing would be to have `createPasswordRec` have a `publicKey` argument, where if it is not `nil` then it does the stuff relating to PGP?
2. How will password salting play into this? Am I doing it correctly by having an empty salt?

### CODE REVIEW

**Comment by j-delaney** [comment]
Delegation with PGP account works. Still working on tests for this and making the UI a bit better

**Comment by grittygrease** [comment]
Are you still working on this?

**Comment by j-delaney** [comment]
I am! Fixing a bug where a unit test is failing, but when I run the commands through the web interface myself it works.

**Comment by kisom** [comment]
This PR has merge conflicts and isn't finished. Closing for now; feel free to re-open.

**Pull request closed without merging**
