### PR TITLE
Implement purge action to remove all delegates, closes #48

### LINKED ISSUE #48: Purge
Admins should be able to purge all delegations.

### PR DESCRIPTION
**Pull request by dullgiulio**
Hope this actually does what's needed.

It removes all non-admin delegates and flushes the cache. Is this correct?

### CODE REVIEW

**Comment by kisom** [comment]
Thanks for the PR @dullgiulio; however, this does the wrong thing. It removes users (i.e. by removing records from the passvault)&mdash;removing delegations should operate on the keycache. Are you still interested in working on this?

**Comment by dullgiulio** [comment]
Sure, I will update the PR later/tomorrow.

**Comment by kisom** [comment]
@dullgiulio Still interested in finishing this? If not, I can take it over.

**Comment by dullgiulio** [comment]
Please take over, I am making you wait too long.

**Comment by kisom** [comment]
Closing this PR, and re-opening from my branch.

**Pull request closed without merging**
