### PR TITLE
Fix for-loop splicing

### PR DESCRIPTION
**Pull request by j-delaney**
Based on [this discussion](https://github.com/cloudflare/redoctober/pull/105#discussion_r46755104). The current method of splicing does not remove every empty string.

### CODE REVIEW

**Comment by j-delaney** [comment]
I realized I also need to update the JS in `redoctober.go`. I'll do that once my changes in `index.html` get okayed.

**Comment by grittygrease** [comment]
The index.html should just be a copy of the string in redoctober.go

**Comment by j-delaney** [comment]
I still want to test this a bit more extensively before it gets merged in

**Comment by grittygrease** [comment]
Are you still working on this PR?

**Comment by j-delaney** [comment]
I am!

**Comment by kisom** [comment]
This PR has merge conflicts and is unfinished. Closing it, feel free to re-open later.

**Pull request closed without merging**
