### PR TITLE
[Urgent]  Patch for Identity Point & Invalid Curve Attacks

### PR DESCRIPTION
**Pull request by Bren2010**
The ECDH (ECIES) library currently allows the decryption of:

1. Messages encrypted with the identity point, which are trivially insecure.
2. Messages encrypted with points on <s>the curve's twist</s> an insecure curve, which <s>(because P-256 isn't twist secure)</s> allows an attacker to fully compromise a user's private key whenever it is delegated.

Thank you & please merge.  Supersedes PR #43.

### CODE REVIEW

**Comment by vkrasnov** [comment]
1. If the message was encrypted with the point at infinity, then anyone can decrypt it and as the output from ScalarMult will always be (0,0), it does not compromise the private key
2. P256 is twist secure

Of course there is no harm in adding the check, but it is hardly urgent.

**Comment by Bren2010** [comment]
@vkrasnov There's more to twist security with NIST curves, right?  (Thank you for commenting, btw.)  In Bernstein's definition of twist security, he's only been given the `x` coordinate by the attacker and he finds the `y` coordinate himself, so the attacker can only choose between the correct curve or one of its quadratic twists (which can only take a small number of forms).

But because we're decoding `x` and `y` coordinates, an attacker can choose *any* curve in the y<sup>2</sup> = x<sup>3</sup> - 3x + B (mod P) space (attacker can chose any `B`), and we don't have any uniform curve structure in that space like we do with the space of quadratic twists of the correct curve.

Please let me know if that's right.

**Comment by vkrasnov** [comment]
What you say is technically correct but it mostly applies to P224 and to secp256k1. P256 have a low enough quadratic twist cofactor, making such attacks unlikely.
However like I said no harm in adding the check. And even better would be using compressed coordinates altogether.

**Comment by Bren2010** [comment]
@vkrasnov Sorry, I guess I'm using the wrong terminology.  This isn't a twist attack, it's an invalid curve attack.  The properties of the curve's twist don't matter because the attacker can just choose a point on a different insecure curve, twist or not.

Compressed coordinates would be better because then it *would* be just a twist attack, but Golang doesn't support them.

**Comment by vkrasnov** [comment]
Because apparently static ECDH is being used, it is a very real threat. In fact that should have been handled in ScalarMult. I suggest you fix it in there too.

**Comment by Bren2010** [comment]
Implicit verification of points has already been rejected [here](https://code.google.com/p/go/issues/detail?id=2445).

> crypto/elliptic is not limited groups with a small cofactor w.r.t. subgroups. But, on the other hand, all current uses of ECDH in the Go code are ephemeral so picking a different curve isn't useful for an attacker.
>
> So I can't prescribe a validation that's sufficient and minimal for everyone. At this level of the code, some understanding is required.

**Comment by grittygrease** [comment]
@Bren2010 Please squash and rebase this PR

**Pull request closed without merging**
